// Generates two artifacts from the messy picks data, for sign-off and app consumption:
//   - docs/PICKS_MAPPING_REPORT.md   (human-readable, for the user to approve)
//   - datasets/picks.normalized.json (structured, for the server to load)
//
// Run with:  npm run report:picks

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Pick, Player, Team } from '@sweepstake/shared';
import { normalizePicks } from './picks';
import { DATASETS_DIR, DOCS_DIR } from './paths';
import { loadTeams } from './teams';

const CONTINGENT_PREFIX = 'playoff-contingent';

function teamById(teams: Team[], id: number): Team | undefined {
  return teams.find((t) => t.id === id);
}

function resolvedLabel(teams: Team[], pick: Pick): string {
  if (pick.teamId !== null) {
    const team = teamById(teams, pick.teamId);
    return team ? `✅ ${team.name} (${team.fifaCode})` : `✅ #${pick.teamId}`;
  }
  if (pick.note?.startsWith(CONTINGENT_PREFIX)) return '⏳ playoff-contingent';
  return '❓ unmatched';
}

function buildReport(teams: Team[], players: Player[], picks: Pick[]): string {
  const matched = picks.filter((p) => p.matched);
  const contingent = picks.filter((p) => !p.matched && p.note?.startsWith(CONTINGENT_PREFIX));
  const unmatched = picks.filter((p) => !p.matched && !p.note?.startsWith(CONTINGENT_PREFIX));

  const pickedIds = new Set(matched.map((p) => p.teamId));
  const unpickedConfirmed = teams.filter((t) => !t.isPlaceholder && !pickedIds.has(t.id));

  // Duplicate confirmed picks (same team picked by more than one player).
  const byTeam = new Map<number, string[]>();
  for (const p of matched) {
    if (p.teamId === null) continue;
    const owner = players.find((pl) => pl.id === p.playerId)?.name ?? `#${p.playerId}`;
    byTeam.set(p.teamId, [...(byTeam.get(p.teamId) ?? []), owner]);
  }
  const duplicates = [...byTeam.entries()].filter(([, owners]) => owners.length > 1);

  const lines: string[] = [];
  lines.push('# Picks Mapping Report');
  lines.push('');
  lines.push(
    '_Generated by `npm run report:picks` from `datasets/player_picks.csv` against ' +
      '`datasets/teams.csv`._',
  );
  lines.push(`_Generated at: ${new Date().toISOString()}._`);
  lines.push('');
  lines.push(
    '**Please review and sign off.** This reconciles the messy picks file against the canonical ' +
      'team list. Pay particular attention to the playoff-contingent picks and any unmatched rows.',
  );
  lines.push('');

  lines.push('## Summary');
  lines.push(`- Total picks: **${picks.length}** (expected 48)`);
  lines.push(`- ✅ Matched to a confirmed team: **${matched.length}**`);
  lines.push(`- ⏳ Playoff-contingent (not yet qualified): **${contingent.length}**`);
  lines.push(`- ❓ Unmatched (needs your input): **${unmatched.length}**`);
  const perPlayerOk = players.every(
    (pl) => picks.filter((p) => p.playerId === pl.id).length === 8,
  );
  lines.push(`- Picks per player: ${perPlayerOk ? 'all 8 ✓' : '⚠️ NOT all 8 — see below'}`);
  lines.push('');

  lines.push('## Findings to confirm');
  lines.push('');
  lines.push(`### ⏳ Playoff-contingent picks (${contingent.length})`);
  lines.push(
    'Picked while still in the playoffs. Each maps to a "Winner Playoff" placeholder **only if ' +
      'it qualifies**, and is treated as *did not qualify* otherwise.',
  );
  lines.push('');
  lines.push('| Player | Pick | Route |');
  lines.push('| --- | --- | --- |');
  for (const p of contingent) {
    const owner = players.find((pl) => pl.id === p.playerId)?.name ?? `#${p.playerId}`;
    const route = p.note?.replace(`${CONTINGENT_PREFIX}: `, '') ?? '';
    lines.push(`| ${owner} | ${p.rawName} | ${route} |`);
  }
  lines.push('');
  lines.push(
    `> Note: there are **${contingent.length}** contingent picks for **6** placeholder slots ` +
      '(4 UEFA + 2 FIFA), so at least one of these is already out.',
  );
  lines.push('');

  lines.push(`### 🚫 Confirmed teams nobody picked (${unpickedConfirmed.length})`);
  if (unpickedConfirmed.length === 0) {
    lines.push('None.');
  } else {
    for (const t of unpickedConfirmed) lines.push(`- ${t.name} (${t.fifaCode}), Group ${t.group}`);
  }
  lines.push('');

  lines.push(`### ♻️ Duplicate picks (${duplicates.length})`);
  if (duplicates.length === 0) {
    lines.push('None — every confirmed team is owned by at most one player.');
  } else {
    for (const [teamId, owners] of duplicates) {
      const team = teamById(teams, teamId);
      lines.push(`- ${team?.name ?? `#${teamId}`}: ${owners.join(', ')}`);
    }
  }
  lines.push('');

  if (unmatched.length > 0) {
    lines.push(`### ❓ Unmatched picks (${unmatched.length})`);
    lines.push('These need a decision (add an alias or correct the source):');
    for (const p of unmatched) {
      const owner = players.find((pl) => pl.id === p.playerId)?.name ?? `#${p.playerId}`;
      lines.push(`- ${owner}: "${p.rawName}"`);
    }
    lines.push('');
  }

  lines.push('## Per-player mapping');
  for (const player of players) {
    const own = picks.filter((p) => p.playerId === player.id);
    lines.push('');
    lines.push(`### ${player.name} (${own.length})`);
    lines.push('| Raw pick | Resolved | Note |');
    lines.push('| --- | --- | --- |');
    for (const p of own) {
      lines.push(`| ${p.rawName} | ${resolvedLabel(teams, p)} | ${p.note ?? ''} |`);
    }
  }
  lines.push('');
  return lines.join('\n');
}

function main(): void {
  const teams = loadTeams();
  const { players, picks } = normalizePicks(teams);

  const report = buildReport(teams, players, picks);
  writeFileSync(join(DOCS_DIR, 'PICKS_MAPPING_REPORT.md'), report, 'utf8');

  const json = {
    generatedAt: new Date().toISOString(),
    players,
    picks,
  };
  writeFileSync(
    join(DATASETS_DIR, 'picks.normalized.json'),
    `${JSON.stringify(json, null, 2)}\n`,
    'utf8',
  );

  const matched = picks.filter((p) => p.matched).length;
  const contingent = picks.filter((p) => !p.matched && p.note?.startsWith(CONTINGENT_PREFIX)).length;
  const unmatched = picks.length - matched - contingent;
  console.log(
    `[report:picks] ${picks.length} picks → ${matched} matched, ${contingent} contingent, ` +
      `${unmatched} unmatched. Wrote docs/PICKS_MAPPING_REPORT.md and datasets/picks.normalized.json`,
  );
}

main();
