// Generates two artifacts from the picks data, for sign-off and app consumption:
//   - docs/PICKS_MAPPING_REPORT.md   (human-readable)
//   - datasets/picks.normalized.json (structured, for the server to load)
//
// Run with:  npm run report:picks

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Pick, Player, Team } from '@sweepstake/shared';
import { normalizePicks } from './picks';
import { DATASETS_DIR, DOCS_DIR } from './paths';
import { loadTeams } from './teams';

const DNQ_PREFIX = 'did not qualify';

function teamById(teams: Team[], id: number): Team | undefined {
  return teams.find((t) => t.id === id);
}

function ownerName(players: Player[], playerId: number): string {
  return players.find((p) => p.id === playerId)?.name ?? `#${playerId}`;
}

function resolvedLabel(teams: Team[], pick: Pick): string {
  if (pick.teamId !== null) {
    const team = teamById(teams, pick.teamId);
    return team ? `✅ ${team.name} (${team.fifaCode})` : `✅ #${pick.teamId}`;
  }
  if (pick.note?.startsWith(DNQ_PREFIX)) return '🚫 did not qualify';
  return '❓ unmatched';
}

function buildReport(teams: Team[], players: Player[], picks: Pick[]): string {
  const matched = picks.filter((p) => p.matched);
  const didNotQualify = picks.filter((p) => !p.matched && p.note?.startsWith(DNQ_PREFIX));
  const unmatched = picks.filter((p) => !p.matched && !p.note?.startsWith(DNQ_PREFIX));

  const pickedIds = new Set(matched.map((p) => p.teamId));
  const unpicked = teams.filter((t) => !pickedIds.has(t.id));

  const byTeam = new Map<number, string[]>();
  for (const p of matched) {
    if (p.teamId === null) continue;
    byTeam.set(p.teamId, [...(byTeam.get(p.teamId) ?? []), ownerName(players, p.playerId)]);
  }
  const duplicates = [...byTeam.entries()].filter(([, owners]) => owners.length > 1);

  const L: string[] = [];
  L.push('# Picks Mapping Report');
  L.push('');
  L.push(
    '_Generated by `npm run report:picks` from `datasets/player_picks.csv` against ' +
      '`datasets/teams.csv`._',
  );
  L.push(`_Generated at: ${new Date().toISOString()}._`);
  L.push('');
  L.push(
    'Reconciles the picks file against the canonical team list. The March 2026 playoff results ' +
      'have been applied to `teams.csv`, so the six qualifying playoff teams are now real entries.',
  );
  L.push('');

  L.push('## Summary');
  L.push(`- Total picks: **${picks.length}** (expected 48)`);
  L.push(`- ✅ Matched to a team: **${matched.length}**`);
  L.push(`- 🚫 Did not qualify (dead pick): **${didNotQualify.length}**`);
  L.push(`- ❓ Unmatched (needs input): **${unmatched.length}**`);
  const perPlayerOk = players.every((pl) => picks.filter((p) => p.playerId === pl.id).length === 8);
  L.push(`- Picks per player: ${perPlayerOk ? 'all 8 ✓' : '⚠️ NOT all 8'}`);
  L.push('');

  L.push('## Findings');
  L.push('');
  L.push(`### 🚫 Picks that did not qualify (${didNotQualify.length})`);
  if (didNotQualify.length === 0) {
    L.push('None.');
  } else {
    L.push('| Player | Pick | Reason |');
    L.push('| --- | --- | --- |');
    for (const p of didNotQualify) {
      const reason = p.note?.replace(`${DNQ_PREFIX}: `, '') ?? '';
      L.push(`| ${ownerName(players, p.playerId)} | ${p.rawName} | ${reason} |`);
    }
  }
  L.push('');

  L.push(`### 🟦 Teams nobody picked (${unpicked.length})`);
  if (unpicked.length === 0) {
    L.push('None — every team is owned.');
  } else {
    for (const t of unpicked) L.push(`- ${t.name} (${t.fifaCode}), Group ${t.group ?? '—'}`);
  }
  L.push('');

  L.push(`### ♻️ Duplicate picks (${duplicates.length})`);
  if (duplicates.length === 0) {
    L.push('None — every team is owned by at most one player.');
  } else {
    for (const [teamId, owners] of duplicates) {
      L.push(`- ${teamById(teams, teamId)?.name ?? `#${teamId}`}: ${owners.join(', ')}`);
    }
  }
  L.push('');

  if (unmatched.length > 0) {
    L.push(`### ❓ Unmatched picks (${unmatched.length})`);
    for (const p of unmatched) L.push(`- ${ownerName(players, p.playerId)}: "${p.rawName}"`);
    L.push('');
  }

  L.push('## Per-player mapping');
  for (const player of players) {
    const own = picks.filter((p) => p.playerId === player.id);
    L.push('');
    L.push(`### ${player.name} (${own.length})`);
    L.push('| Raw pick | Resolved | Note |');
    L.push('| --- | --- | --- |');
    for (const p of own) {
      L.push(`| ${p.rawName} | ${resolvedLabel(teams, p)} | ${p.note ?? ''} |`);
    }
  }
  L.push('');
  return L.join('\n');
}

function main(): void {
  const teams = loadTeams();
  const { players, picks } = normalizePicks(teams);

  writeFileSync(
    join(DOCS_DIR, 'PICKS_MAPPING_REPORT.md'),
    buildReport(teams, players, picks),
    'utf8',
  );
  writeFileSync(
    join(DATASETS_DIR, 'picks.normalized.json'),
    `${JSON.stringify({ generatedAt: new Date().toISOString(), players, picks }, null, 2)}\n`,
    'utf8',
  );

  const matched = picks.filter((p) => p.matched).length;
  const dnq = picks.filter((p) => !p.matched && p.note?.startsWith(DNQ_PREFIX)).length;
  const unmatched = picks.length - matched - dnq;
  console.log(
    `[report:picks] ${picks.length} picks → ${matched} matched, ${dnq} did-not-qualify, ` +
      `${unmatched} unmatched. Wrote docs/PICKS_MAPPING_REPORT.md and datasets/picks.normalized.json`,
  );
}

main();
